services:
  cobbler:
    image: cobbler:3.3.7
    container_name: cobbler-3.7
    build:
      context: .
    env_file:
      - .env
    secrets:
      - cobbler_root_password
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - cobbler_data:/var/lib/cobbler
      - cobbler_www:/var/www/cobbler
      - ./isos:/isos
      - /mnt:/mnt:rshared

secrets:
  cobbler_root_password:
    file: ./secrets/cobbler_root_password.txt

volumes:
  cobbler_data:
  cobbler_www: