[program:cobblerd]
command=/usr/local/bin/cobblerd -F
priority=50
startsecs=10
autostart=false
autorestart=true
exitcodes=0
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0