[program:dhcpd]
command=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid
priority=40
startsecs=3
autorestart=true
killasgroup=true
stopasgroup=true
autostart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
